# -------- Datasource Config --------
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    datasource:
        #Local database
        #url: jdbc:mysql://127.0.0.1:3306/testing?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        #username: tommy
        #password: 7Kcr4iv3

        #Heroku ClearDB
        url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_c013c43b09ce49a?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        username: b370d0c06a6ecd
        password: e3218523

        connection-test-query: "SELECT 1"
        test-while-idle: true
        test-on-borrow: false
    #用 gson swagger 會不能用
    #http:
    #   converters:
    #      preferred-json-mapper: gson

# --------- MyBatis 若用 xml 要加這個 ---------        
#mybatis:
#    mapperLocations: classpath*:**/sqlmappers/*.xml

# -------- Mail Config --------
mail:
    username: exfantasy7wolves
    password: ilovebmw

# -------- Custom Config --------    
custom:
    admins:
        - tommy.yeh1112@gmail.com
        - alicechen1013@gmail.com

    loginMaxAttempt: 3
    
    blockTimeMins: 5