# -------- Datasource Config --------
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    datasource:
        # Local database
        url: jdbc:mysql://127.0.0.1:3306/testing?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        username: tommy
        password: 7Kcr4iv3

        # Heroku ClearDB
        # url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_c013c43b09ce49a?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        # username: b370d0c06a6ecd
        # password: e3218523

        # Connection Setting
        # Ref: http://stackoverflow.com/questions/30451470/connection-to-db-dies-after-424-in-spring-boot-jpa-hibernate
        max-active: 5
        initial-size: 3
        max-idle: 5
        min-idle: 3
        test-while-idle: true
        test-on-borrow: true
        validation-query: "SELECT 1"
        connection-test-query: "SELECT 1"

# -------- Mail Config --------
mail:
    username: exfantasy7wolves
    password: meywlnxyckgerkgw        
        
# -------- Custom Config --------    
custom:
    admins:
        - tommy.yeh1112@gmail.com
        - alicechen1013@gmail.com

    loginMaxAttempt: 3
    
    blockTimeMins: 5