# -------- Datasource Config --------
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    datasource:
        # Local database
        # url: jdbc:mysql://127.0.0.1:3306/testing?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        # username: tommy
        # password: 7Kcr4iv3

        # Heroku ClearDB
        url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/heroku_c013c43b09ce49a?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        username: b370d0c06a6ecd
        password: e3218523

        # Connection Setting
        # Ref: http://stackoverflow.com/questions/30451470/connection-to-db-dies-after-424-in-spring-boot-jpa-hibernate
        # Ref: https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku
        max-active: 10
        max-idle: 5
        min-idle: 2
        initial-size: 5
        removeAbandoned: true
        test-while-idle: true
        test-on-borrow: true
        validation-query: "SELECT 1"
        connection-test-query: "SELECT 1"
    
    # http://stackoverflow.com/questions/37540028/how-to-set-the-max-size-of-upload-file
    http:
        multipart:
            max-file-size: 10MB
            max_request-size: 10MB
        
# -------- Mail Config --------
mail:
    username: exfantasy7wolves
    password: meywlnxyckgerkgw
    
# -------- Amazon S3 Config --------
aws:
    s3:
        bucket: tommy-web-service
        accessKey: AKIAJFF63NJWTN55KNDQ
        secretKey: 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            
        
# -------- Custom Config --------    
custom:
    admins:
        - tommy.yeh1112@gmail.com
        - alicechen1013@gmail.com

    loginMaxAttempt: 3
    
    blockTimeMins: 5